### ISSUE TITLE
link naar de README gaat werkt niet

### ISSUE THREAD

**Issue by mjrider** [Hilbrand/verkiezingsuitslagen#1]
Als je op de link README klinkt op de website kom je uit op
https://hilbrand.github.io/verkiezingsuitslagenhttps://www.github.com/hilbrand/verkiezingsuitslagen  wat een 404 geeft ipv de verwachte locatie https://www.github.com/hilbrand/verkiezingsuitslagen

**Comment by Hilbrand** [comment]
Bedankt voor melden. Had het al gezien, maar dacht dat ik het al gefixed had, maar blijkbaar niet...
